//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int id_libro { get; set; }
        public string nombre { get; set; }
        public string autor { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal precio { get; set; }
        public int id_sucursal { get; set; }
        public int id_categoria { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
